// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQxMGV5zGtud77V5WI9E9C_rZ88OXICaA',
    appId: '1:826084846729:web:0ec06178223c9fc4022a58',
    messagingSenderId: '826084846729',
    projectId: 'yumyum-7d3f4',
    authDomain: 'yumyum-7d3f4.firebaseapp.com',
    storageBucket: 'yumyum-7d3f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ZoTAzDRqs7CA3ei7irm7uxrOCgac79I',
    appId: '1:826084846729:android:6faba7ed20e8762a022a58',
    messagingSenderId: '826084846729',
    projectId: 'yumyum-7d3f4',
    storageBucket: 'yumyum-7d3f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjoegocPa9NhM-3EIWVlDqxhR8qE3OlVE',
    appId: '1:826084846729:ios:8447b191a7366de6022a58',
    messagingSenderId: '826084846729',
    projectId: 'yumyum-7d3f4',
    storageBucket: 'yumyum-7d3f4.appspot.com',
    iosBundleId: 'com.example.firebasetest2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjoegocPa9NhM-3EIWVlDqxhR8qE3OlVE',
    appId: '1:826084846729:ios:8447b191a7366de6022a58',
    messagingSenderId: '826084846729',
    projectId: 'yumyum-7d3f4',
    storageBucket: 'yumyum-7d3f4.appspot.com',
    iosBundleId: 'com.example.firebasetest2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQxMGV5zGtud77V5WI9E9C_rZ88OXICaA',
    appId: '1:826084846729:web:8817bce7788059b9022a58',
    messagingSenderId: '826084846729',
    projectId: 'yumyum-7d3f4',
    authDomain: 'yumyum-7d3f4.firebaseapp.com',
    storageBucket: 'yumyum-7d3f4.appspot.com',
  );

}