// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Qau0h5Dlp_Ch2RwGN3vwNnUqcTX51xY',
    appId: '1:869783138598:web:9cbaec6cf6b629ef3611e7',
    messagingSenderId: '869783138598',
    projectId: 'capp-2df2d',
    authDomain: 'capp-2df2d.firebaseapp.com',
    storageBucket: 'capp-2df2d.firebasestorage.app',
    measurementId: 'G-BH29Y0F26K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2irOhF7pgtNIPweRfFxhpp0YPtGCWcbI',
    appId: '1:869783138598:android:1c3534c28b95c6423611e7',
    messagingSenderId: '869783138598',
    projectId: 'capp-2df2d',
    storageBucket: 'capp-2df2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMI9kLOQwQXMYBDMLR_wf38I28SZ7rMTc',
    appId: '1:869783138598:ios:257785614c6e377e3611e7',
    messagingSenderId: '869783138598',
    projectId: 'capp-2df2d',
    storageBucket: 'capp-2df2d.firebasestorage.app',
    iosClientId: '869783138598-cjriaj5d3vdgn4vv9db97819vshgplvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.cap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMI9kLOQwQXMYBDMLR_wf38I28SZ7rMTc',
    appId: '1:869783138598:ios:257785614c6e377e3611e7',
    messagingSenderId: '869783138598',
    projectId: 'capp-2df2d',
    storageBucket: 'capp-2df2d.firebasestorage.app',
    iosClientId: '869783138598-cjriaj5d3vdgn4vv9db97819vshgplvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.cap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9Qau0h5Dlp_Ch2RwGN3vwNnUqcTX51xY',
    appId: '1:869783138598:web:3e0ea49a3990527b3611e7',
    messagingSenderId: '869783138598',
    projectId: 'capp-2df2d',
    authDomain: 'capp-2df2d.firebaseapp.com',
    storageBucket: 'capp-2df2d.firebasestorage.app',
    measurementId: 'G-ZXCV39QWMV',
  );
}
